name: Lint

concurrency:
  group: lint-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  actions: read
  checks: write
  contents: read
  pull-requests: read

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Trunk Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Trunk Check
        uses: trunk-io/trunk-action@v1
        with:
          check-mode: all
